### ISSUE TITLE
Help Required in Automation

### ISSUE THREAD

**Issue by Smartgendeveloper** [tilmanmoser/bbb-video-download#13] opened 2020-10-08 07:44 UTC
Hi,

First of thank you very much for creating such a useful script. I tried your script but facing some issues. below is the modified script and it's giving me an error like access denied

#!/bin/bash

BASEPATH=/var/bigbluebutton/published/presentation
OUTPUTPATH=/opt/bbb-video-download/mp4recording
LOGFILE=/var/log/videogenerator.log

for presentation in ${BASEPATH}/*; do
        ID=$(basename $presentation)
        VIDEOFILE="${OUTPUTPATH}/${ID}/${ID}.mp4"
        echo "$(date) Processing ${VIDEOFILE}" >> $LOGFILE
        #Check if mp4 already exists
        if [ ! -e $VIDEOFILE ]; then
                sudo -u bigbluebutton bash -c  cd /opt/bbb-video-download;  node ./node12/bin/node index.js -i $presentation -o $VIDEOFILE >> $LOGFILE 2>> $LOGFILE
                if [ ! -e $VIDEOFILE ]; then
                        echo "Conversion of ${ID} failed" >> $LOGFILE
                fi
        else
                echo "$(date) ${ID} already has a video file - skipping" >> $LOGFILE
        fi
        echo "======================================================" >> $LOGFILE
done

Can you help out why it's giving such error?

Thanking you.

**Comment by wolbernd** [comment] 2020-10-08 08:07
@Smartgendeveloper Please note that this script is NOT part of bbb-video-download. It's just a script I cobbled together.

An access denied error is probably due to permissions. Without knowing your setup I can't say exactly where the cause is. My guess is the LOGFILE. If you run this script as a non-root user you probably don't have write access to /var/log so you either have to change the LOGFILE variable or create the LOGFILE as root and set the permission so your user can write it.

**Comment by Smartgendeveloper** [comment] 2020-10-08 08:13
In the log file its showing below error : 

Thu Oct  8 08:10:32 UTC 2020 Processing /opt/bbb-video-download/mp4recording/108f3da1c5b1fa7ce182b5440a35b0946cd06e82-1601100629069/108f3da1c5b1fa7ce182b5440a35b0946cd06e82-1601100629069.m$
/opt/bbb-video-download/node12/bin/node:1
(function (exports, require, module, __filename, __dirname) { ^?ELF^B^A^A^C
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Conversion of 108f3da1c5b1fa7ce182b5440a35b0946cd06e82-1601100629069 failed

**Comment by wolbernd** [comment] 2020-10-08 08:21
Hm this looks like it might be a bug in the bbb-vide-download. To be sure that the script is running with the correct arguments could you check the value of `$presentation` ? Just change the line `echo "$(date) Processing ${VIDEOFILE}" >> $LOGFILE` to `echo "$(date) Processing ${presentation} - ${VIDEOFILE}" >> $LOGFILE

**Comment by Smartgendeveloper** [comment] 2020-10-08 08:26
Here is the log with updated .sh file

Thu Oct  8 08:24:58 UTC 2020 Processing /var/bigbluebutton/published/presentation/09b3e5c46ff43b6e871b4e90b477ccdebfc22a5c-1601973464896 -
/opt/bbb-video-download/mp4recording/09b3e5c46ff43b6e871b4e90b477ccdebfc22a5c-1601973464896.mp4
/opt/bbb-video-download/node12/bin/node:1
(function (exports, require, module, __filename, __dirname) { ^?ELF^B^A^A^C
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
Conversion of 09b3e5c46ff43b6e871b4e90b477ccdebfc22a5c-1601973464896 failed

**Comment by wolbernd** [comment] 2020-10-08 08:32
I'm not sure if this is the cause but in this line: `sudo -u bigbluebutton bash -c cd /opt/bbb-video-download; node ./node12/bin/node index.js -i $presentation -o $VIDEOFILE >> $LOGFILE 2>> $LOGFILE` you call node two times (once the locally installed and once the one in /opt/bbb-video-download/node12). You probably might want to remove the first `node`. If that won't fix it it's probably a bug in the video downloader and I can't help you.

**Comment by Smartgendeveloper** [comment] 2020-10-08 08:39
Thank you very much for your prompt reply. Actually, I also suspected the same thing which you mentioned above. Let me do some tweak with that particular command and if works will get with my feedback.


Again thank you very much for spending your precious time

**Comment by Smartgendeveloper** [comment] 2020-10-08 09:03
Okay. Here is my Updated script and its working fine. The batch job started and working as expected.


#!/bin/bash

BASEPATH=/var/bigbluebutton/published/presentation
OUTPUTPATH=/opt/bbb-video-download/mp4recording
LOGFILE=/opt/bbb-video-download/log/videogenerator.log

for presentation in ${BASEPATH}/*; do
        ID=$(basename $presentation)
        VIDEOFILE="${OUTPUTPATH}/${ID}.mp4"
        echo "$(date) Processing ${presentation} - ${VIDEOFILE}" >> $LOGFILE
        #Check if mp4 already exists
        if [ ! -e $VIDEOFILE ]; then
                sudo ./node12/bin/node index.js -i $presentation -o $VIDEOFILE >> $LOGFILE 2>> $LOGFILE
                if [ ! -e $VIDEOFILE ]; then
                        echo "Conversion of ${ID} failed" >> $LOGFILE
                fi
        else
                echo "$(date) ${ID} already has a video file - skipping" >> $LOGFILE
        fi
        echo "======================================================" >> $LOGFILE
done



Thank you very much

**Comment by wolbernd** [comment] 2020-10-08 09:22
No problem. If this problem is fixed for you please close this issue.

**Closed** 2020-10-08 09:23 UTC
