### ISSUE TITLE
unable to get the mp4 file

### ISSUE THREAD

**Issue by rexon07** [tilmanmoser/bbb-video-download#22] opened 2020-10-26 10:48 UTC
hi,

i tried coverting an 4 mins recording which worked fine. but when tried to convert an 1hr recording there is no mp4 file for it.
but the recording is published . 
logs:
I, [2020-10-26T09:17:25.949678 #21299]  INFO -- : Create downloadable video for [ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440] start
I, [2020-10-26T09:30:13.757666 #21299]  INFO -- : [Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440', output='/var/bigbluebutton/published/presen$
  env: { chunksize: 25 }
}

I, [2020-10-26T09:30:13.757771 #21299]  INFO -- : Create downloadable video for [ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440] end
I, [2020-10-26T09:30:14.341403 #21795]  INFO -- : Task: Getting meeting metadata
I, [2020-10-26T09:30:14.508124 #21795]  INFO -- : Recording Ready Notify for [ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440] starts
I, [2020-10-26T09:30:14.508199 #21795]  INFO -- : Recording Ready notify ends
I, [2020-10-26T11:27:37.209539 #29170]  INFO -- : Task: Getting meeting metadata
I, [2020-10-26T11:27:37.379765 #29170]  INFO -- : Create downloadable video for [ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440] start
I, [2020-10-26T11:40:26.295578 #29170]  INFO -- : [Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440', output='/var/bigbluebutton/published/presen$
  env: { chunksize: 25 }
}

I, [2020-10-26T11:40:26.295701 #29170]  INFO -- : Create downloadable video for [ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440] end
I, [2020-10-26T11:40:26.880164 #29751]  INFO -- : Task: Getting meeting metadata
I, [2020-10-26T11:40:27.044162 #29751]  INFO -- : Recording Ready Notify for [ed35d717c594a4dda2fb1861866c6d50f50dd605-1603694758440] starts
I, [2020-10-26T11:40:27.044242 #29751]  INFO -- : Recording Ready notify ends

looking for help.
thanks.

**Comment by tilmanmoser** [comment] 2020-10-26 11:36
Please have a look at the command you use to call the script. The output file has a weird variable in it's name.

**Comment by rexon07** [comment] 2020-10-26 11:59
Hi @tilmanmoser  ,

thanks for your reply, the used the bbb-record --rebuild <presentation id>.
which worked fine for an short 4 min recording. But 1 hr recording iam unable to get the mp4 file.

**Comment by wsamipw** [comment] 2020-10-27 13:54
I encountered the same issue.

**Comment by tilmanmoser** [comment] 2020-10-28 09:15
I'll have a look into this.

**Comment by maheshmadmax** [comment] 2020-10-29 09:53
I too faced same issue..

if recording is more than 45 min, the script doesnt convert to mp4

**Comment by miriyusifli** [comment] 2020-10-29 10:04
I have tested a 2 hours recording, it was converted successfully.

**Comment by tilmanmoser** [comment] 2020-11-01 09:28
Rebuild seems not to work when the raw data was already purged. Since my script doesn't need the raw data, try to run it manually on your recording. If this works, it's not related to the video length. However, I will provide different ways to run the script for different scenarios (immediately, manually, older recordings, etc...). Please stay tuned.

**Comment by maheshmadmax** [comment] 2020-11-04 04:12
I too faced same issue..

if recording is more than 45 min, the script doesnt convert to mp4




Input #6, matroska,webm, from '/var/bigbluebutton/published/presentation/ec465c8bef27ac7336108844167ab571e8bd669c-1603943292921/video/webcams.webm':
  Metadata:
    creation_time   : 2020-10-29T08:17:35.000000Z
    ENCODER         : Lavf58.29.100
  Duration: 01:17:45.72, start: -0.007000, bitrate: 53 kb/s
    Stream #6:0: Video: vp9 (Profile 0), yuv420p(tv, progressive), 640x480, SAR 1:1 DAR 4:3, 24 fps, 24 tbr, 1k tbn, 1k tbc (default)
    Metadata:
      ENCODER         : Lavc58.54.100 libvpx-vp9
      DURATION        : 01:17:45.716000000
    Stream #6:1: Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      ENCODER         : Lavc58.54.100 libopus
      DURATION        : 01:17:45.707000000
[ffmetadata @ 0x560d208f0480] Chapter end time 4665699 before start 9822400
./tmp/ec465c8bef27ac7336108844167ab571e8bd669c-1603943292921/ffmetadata.txt: Cannot allocate memory

    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at Processor.createVideo (/opt/bbb-video-download/modules/processor.js:65:26)
    at async process (/opt/bbb-video-download/index.js:55:9) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 32 2e 34 2d 31 75 62 75 6e 74 75 30 2e 31 62 62 62 31 7e 31 36 2e 30 34 2e 31 20 43 6f 70 79 72 69 ... 6539 more bytes>
  ],
  pid: 27489,
  stdout: <Buffer >,
  stderr: <Buffer 66 66 6d 70 65 67 20 76 65 72 73 69 6f 6e 20 34 2e 32 2e 34 2d 31 75 62 75 6e 74 75 30 2e 31 62 62 62 31 7e 31 36 2e 30 34 2e 31 20 43 6f 70 79 72 69 ... 6539 more bytes>
}

I, [2020-10-29T09:21:13.751967 #27003]  INFO -- : Create downloadable video for [ec465c8bef27ac7336108844167ab571e8bd669c-1603943292921] end
I, [2020-10-29T09:21:13.983373 #27491]  INFO -- : Task: Getting meeting metadata
I, [2020-10-29T09:21:14.001680 #27491]  INFO -- : Recording Ready Notify for [ec465c8bef27ac7336108844167ab571e8bd669c-1603943292921] starts
I, [2020-10-29T09:21:14.001730 #27491]  INFO -- : Recording Ready notify ends
I, [2020-11-02T13:01:42.886915 #18932]  INFO -- : Task: Getting meeting metadata
I, [2020-11-02T13:01:42.939161 #18932]  INFO -- : Create downloadable video for [ec465c8bef27ac7336108844167ab571e8bd669c-1604289701657] start
I, [2020-11-02T13:32:45.650065 #18932]  INFO -- : [Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/ec465c8bef27ac7336108844167ab571e8bd669c-1604289701657', output='/var/bigbluebutton/published/presentation/ec465c8bef27ac7336108844167ab571e8bd669c-1604289701657/video.mp4'),
  env: { chunksize: 25 }
}

I, [2020-11-02T13:32:45.650124 #18932]  INFO -- : Create downloadable video for [ec465c8bef27ac7336108844167ab571e8bd669c-1604289701657] end
I, [2020-11-02T13:32:45.999050 #19883]  INFO -- : Task: Getting meeting metadata
I, [2020-11-02T13:32:46.048896 #19883]  INFO -- : Recording Ready Notify for [ec465c8bef27ac7336108844167ab571e8bd669c-1604289701657] starts
I, [2020-11-02T13:32:46.048960 #19883]  INFO -- : Recording Ready notify ends
I, [2020-11-02T15:35:54.378892 #22544]  INFO -- : Task: Getting meeting metadata
I, [2020-11-02T15:35:54.412360 #22544]  INFO -- : Create downloadable video for [5c13b33f4cf89d4f0607389e7333eebaed8e116c-1604321872752] start
I, [2020-11-02T15:44:19.056357 #22544]  INFO -- : [Start] Rendering downloadable video for BBB presentation  {
  args: Namespace(input='/var/bigbluebutton/published/presentation/5c13b33f4cf89d4f0607389e7333eebaed8e116c-1604321872752', output='/var/bigbluebutton/published/presentation/5c13b33f4cf89d4f0607389e7333eebaed8e116c-1604321872752/video.mp4'),
  env: { chunksize: 25 }
}

I, [2020-11-02T15:44:19.056425 #22544]  INFO -- : Create downloadable video for [5c13b33f4cf89d4f0607389e7333eebaed8e116c-1604321872752] end
I, [2020-11-02T15:44:19.326840 #22725]  INFO -- : Task: Getting meeting metadata
I, [2020-11-02T15:44:19.360249 #22725]  INFO -- : Recording Ready Notify for [5c13b33f4cf89d4f0607389e7333eebaed8e116c-1604321872752] starts
I, [2020-11-02T15:44:19.360302 #22725]  INFO -- : Recording Ready notify ends

**Comment by tilmanmoser** [comment] 2020-11-05 10:59
Memory issue was fixed with v1.2.1

**Closed by tilmanmoser** 2020-11-05 10:59 UTC

**Comment by chinmay81098** [comment] 2021-03-05 04:41
Hi,
I have added the script successfully,  but the mp4 file is not created. From logs I can confirm that the script is running

 [2021-03-04T17:23:15.142837 #5581]  INFO -- : Task: Getting meeting metadata
I, [2021-03-04T17:23:15.164597 #5581]  INFO -- : Create downloadable video for [537fd4a41e4981742edbda56b7c7245ee20d93b4-1614878360274] start
I, [2021-03-04T17:23:15.165403 #5581]  INFO -- :
I, [2021-03-04T17:23:15.165440 #5581]  INFO -- : Create downloadable video for [537fd4a41e4981742edbda56b7c7245ee20d93b4-1614878360274] end
I, [2021-03-04T17:23:15.412242 #5584]  INFO -- : Task: Getting meeting metadata
I, [2021-03-04T17:23:15.434041 #5584]  INFO -- : Recording Ready Notify for [537fd4a41e4981742edbda56b7c7245ee20d93b4-1614878360274] starts
I, [2021-03-04T17:23:15.434112 #5584]  INFO -- : Recording Ready notify ends
I, [2021-03-04T18:33:22.488089 #9766]  INFO -- : Task: Getting meeting metadata
I, [2021-03-04T18:33:22.497444 #9766]  INFO -- : Create downloadable video for [537fd4a41e4981742edbda56b7c7245ee20d93b4-1614882363641] start
I, [2021-03-04T18:33:22.498211 #9766]  INFO -- :
I, [2021-03-04T18:33:22.498242 #9766]  INFO -- : Create downloadable video for [537fd4a41e4981742edbda56b7c7245ee20d93b4-1614882363641] end
I, [2021-03-04T18:33:22.717047 #9770]  INFO -- : Task: Getting meeting metadata
I, [2021-03-04T18:33:22.726264 #9770]  INFO -- : Recording Ready Notify for [537fd4a41e4981742edbda56b7c7245ee20d93b4-1614882363641] starts
I, [2021-03-04T18:33:22.726316 #9770]  INFO -- : Recording Ready notify ends

Is there supposed to be a log between start and end ?
